name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  build-test:
    uses: DavidArthurCole/EggBasket/.github/workflows/dotnet-ci.yml@master
    with:
      solution: SyncKit.slnx
      dotnet-version: "10.0.x"
